---
title: 'Cognitive Aspects of Software Development: a SMS'
output:
  html_document: 
    df_print: tibble
    fig_caption: yes
editor_options: 
  chunk_output_type: inline
---

```{r}
# Keep things nice and tidy, all libraries go here
library(readxl)
library(tidyverse)
library(knitr)
library(kableExtra)
library(svglite)
```
```{r}
data <- read_excel("data.xlsx", skip = 1)
data <- data %>% filter(is.na(Exclude))
```

# Visualizing number of publications over time
```{r}
ggplot(data, aes(x=as.factor(Year))) + 
  geom_bar() +  
  ylab("Number of publications") +
  xlab("Year") + 
  geom_text(stat='count', aes(label=..count..), vjust=2, color="white", size = 2.5) + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
ggsave("yearly_distribution.eps")
```


```{r}

# Cleaning not needed values 
data<-data %>% 
    mutate(Academia = replace(Academia, Academia == "?", NA)) %>%
    mutate(Industry = replace(Industry, Industry == "?", NA))

data<-data %>%
  mutate(Type = case_when(is.na(Academia) & is.na(Industry) ~ "None", 
                       Academia == "1.0" & is.na(Industry) ~ "Academia",
                       Industry == "1.0" & is.na(Academia) ~ "Industry", 
                       TRUE ~ "Both"))
```

# Number of publications according to their type
```{r}
data %>% 
  mutate(Type = fct_infreq(Type, ordered = T)) %>% 
ggplot(aes(x=Type)) + 
  geom_bar(width = .5) +
  xlab("Type of publication") + 
  ylab("Number of publications") + 
  geom_text(stat='count', aes(label=..count..), vjust=3, color="white", size = 4) +
  theme_bw()
ggsave("academia_industry_distribution.eps")
```

# Number of publications categorized according to SWEBoK Areas. 
A publication can be in more than one category at the same time.

```{r}
data %>% 
  select(7:21) %>% # selecting columns corresponding to the SWEBoK Areas
  mutate_all(replace_na,0) %>% 
  summarise_all(sum) %>% 
  gather(key = "SWEBOKArea", value = "publications", 1:15) %>% 
  arrange(-publications) %>%  
  mutate(SWEBOKArea = factor(SWEBOKArea, SWEBOKArea)) %>% 
  ggplot(aes(x=SWEBOKArea, y=publications)) + 
  geom_bar(stat="identity") + 
  geom_text(aes(label=publications), vjust=-0.3, color="black", size = 4) + 
  xlab("SWEBoK Area") + 
  ylab("Number of publications") +
  theme_bw()

ggsave("swebok_distribution.eps")
```

# Co-occurrences of SWEBoK Areas
```{r}
data %>% 
  select(7:21) %>% # selecting columns corresponding to the SWEBoK Areas
  mutate_all(replace_na,0) %>% 
  as.matrix() %>% 
  crossprod() %>% 
  kable() %>%
  kable_styling("striped", full_width = T) %>%
  column_spec(1, bold = T)
```

```{r}
x <- data %>% select(7:21, matches('Attention|Memory|Cognitive load|CL$|Problem solving|Reasoning|Decision making|Errors| biases$' )) %>%
  mutate_all(replace_na, 0) %>%
  mutate(`Problem solving`, `Problem solving` = as.numeric(`Problem solving`)) %>% 
  gather(key="SWEBOK", value = pubs, 1:15) %>% # use SWEBOK area as factor
  filter(pubs == 1) %>% # select areas for which there are publications
  group_by(SWEBOK) %>% 
  summarise_all(sum) %>% # number of publication for each area 
  select(-pubs) %>%  # remove pubs to reuse it later
  gather(key = "Taxonomy", value = "count", 2:17) %>%  # count publications in each cognitive taxonomy area
  mutate(label = str_replace(as.character(count), "^0", "")) # add label for later
```
```{r}
# Bubble plot
x <- arrange(x, Taxonomy)
xf<-x$Taxonomy
xfu<-unique(xf)
x$Taxonomy<-factor(xf,levels=xfu)
p<-ggplot(x)
p + geom_point(aes(x = fct_infreq(SWEBOK), y = fct_rev(Taxonomy)), size=x$count*1.6, shape=21, fill="white", alpha=0.60) +
geom_text(aes(x = fct_infreq(SWEBOK), y = fct_rev(Taxonomy), label=label), size=2) +
theme(axis.text.x = element_text(angle = 45, hjust = 1.1, size=9,colour="black"), axis.text.y = element_text(size=8,colour="black"), axis.title.x = element_text(size=10), axis.title.y = element_text(size=10,colour = "black",vjust=0.12), panel.grid.major = element_line(linetype = "dashed", size=0.1, color="black"))+
  labs(x="SWEBOK Area",y = "Taxonomy Area")
theme_bw()
ggsave("swebok_taxonomy_bubble.eps")
```

